### PR TITLE
Motion blur mode

### PR DESCRIPTION
**Pull request by Mengnumbal3375**
I was expecting a motion blur option (like RSMB). So it would track the object in the frame and add motion blur based on 1 frame in front and behind the current frame, all the way to the last frame. 

For more details, see this video
https://youtu.be/9eqyoH7Sxjc?si=-zbvo9kVinPbyYCu

Even if we use motion blur after interpolation. It will be able to cover the warp frame.

### CODE REVIEW

**Comment by banjaminicc** [comment]
Motion blur can always be added back in editing software, there's already a specific AI motion blur programme from the DAIN.app team. 

There's probably a better allocation to time for hzwer to improve the models than adding motion blur lol

**Comment by Mengnumbal3375** [comment]
Sorry in advance. I may not know anything yet. From my point of view, I was surprised that there is a tool like this that can be used in google colab. So I wanted to ask if motion blur can also be applied here (no coercion). 

And your statement about editing software I admit is true. But you need to know that I am here only using a phone (no pc). Although there is motion blur software, its features are limited (warp, bad result, etc) because the phone system is still weak (unlike pc). So I just rely on google colab to do it. So maybe if you have a better solution seen from my condition.

Again, please forgive me for not knowing anything. Thanks

**Comment by masahiroteraoka** [comment]
There may be two-ways or more. 

First one is.....  Actually RIFE produces optical-flow-vector, which is similar to motion-vector. We may need a bit trick, because RIFE is doing like 'Temporal-Pincer'(TENET), so we might need to give up this smart solution, but still we can use it for 'ONE-WAY', eg: Let's say we are at frame #5, usually we'll see trails, from frame 4.5 to frame 5.5 in motionblur. Firstly we create optical-flow-vector with frame #4 and frame #5, as timestep =0.5, in this case RIFE is producing an optical-flow-vector (Let's say v0) which makes frame#4 into frame #4.5 (flow[:, :2]) and  one more vector (Let's say v1) which makes frame #5 into frame #4.5 (flow[:,2:4]), so we can use the second one (v1), and so that we can push pixels where they are at frame #4.5 a little by little with v1 and image tensor of frame#5, for example (maybe the optical flow slicing is opposite, sorry!)

warped_img0 = None 
for i in range(10):
    warped_img0 += warp(img0, flow[:,2:4]*0.1*float(i))
warped_img0 /= 10.
        
this will give us kinda motion trails(blur)
And then we can do same this for frame5-5.5.
This process will make trails which we can see in motionblur.

Second is just making RIFE do its job 10 times, so I mean from frame 4.5 - 5.5, we make frame #4.5, #4.6, #4.7, #4.8,#4.9, #5.0, #5.1, #5.2........ for example , then will get sum of them. and divide by 10. this one costs a bit.  But it might show us fancy 'curved-motion-blur'.

**Comment by NevermindNilas** [comment]
There are plenty of tools that already do motion blur using Rife and Frame averaging with ( I assume ) kernels. 
[Smoothie-rs](https://github.com/couleur-tweak-tips/smoothie-rs)

There's also other alternatives that utilize " SVPFlow "
[blur](https://github.com/f0e/blur)

There's no real reason to tackle this subject.

**Pull request closed without merging**
